run:
  data: PretrainBlendsArtifact-tiny:latest
  env:
    container: nvcr.io/nvidian/nemo:26.02.super.rc1
    # startup_commands:  # Commands to run before training starts
    #   - "echo 'Setting up training environment...'"
    #   - "mkdir -p /nemo_run/pretrain"

recipe:
  _target_: megatron.bridge.recipes.nemotronh.nemotron_3_nano.nemotron_3_nano_pretrain_config
  per_split_data_args_path: ${art:data,path}/blend.json

logger:
  log_interval: 10
  wandb_project: ${run.wandb.project}   # Set from env.toml [wandb]
  wandb_entity: ${run.wandb.entity}     # Set from env.toml [wandb]

checkpoint:
  save: /nemo_run/pretrain
  save_interval: 20